version: '3'

services:

  grideye_simulator:
    container_name: grideye_sim
    build: ../images/GridEye_Simulator
    ports:
      - 2404:2404
    volumes:
      - applicativeLogs:/logs

  filebeat:
    container_name: fbeat
    build: ../images/filebeat
    volumes:
      - applicativeLogs:/usr/share/filebeat/logs

  metricbeat:
    container_name: mbeat
    build: ../images/metricbeat
    depends_on:
      - db

  # Non-persistant DB
  db:
    image: postgres:12.1
    container_name: postgres
    ports:
      - 5432:5432


volumes:
  applicativeLogs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/jael/Data/Cours/TB/Elastic_Stack/docker/docker-field/images/GridEye_Simulator/logs'
