version: '3'

services:

  grideye_simulator:
    container_name: grideye_sim
    build: ../images/GridEye_Simulator
    restart: on-failure
    ports:
      - 2404:2404
    volumes:
      - applicativeLogs:/logs

  filebeat:
    container_name: fbeat
    build:
            context: ../images/filebeat
            args:
                    elastic_version: 7.8.0
    volumes:
      - applicativeLogs:/usr/share/filebeat/logs

  metricbeat:
    container_name: mbeat
    build:
            context: ../images/metricbeat
            args:
                    elastic_version: 7.8.0
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Non-persistant DB
  db:
    container_name: postgres
    build: ../images/postgresql
    ports:
      - 5432:5432


volumes:
  applicativeLogs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media/jael/Data/Cours/TB/Elastic_Stack/docker/docker-field/images/GridEye_Simulator/logs'
